import { CitySeed } from '../types';

export const citySeeds: CitySeed[] = [
  {
    name: 'Denver',
    state: 'CO',
    latitude: 39.7392,
    longitude: -104.9903,
    search_keywords: ['denver', 'denver co', 'downtown denver', 'central denver'],
    priority: 1,
  },
  {
    name: 'Parker',
    state: 'CO',
    latitude: 39.5186,
    longitude: -104.7614,
    search_keywords: ['parker', 'parker co', 'parker colorado'],
    priority: 1,
  },
  {
    name: 'Castle Rock',
    state: 'CO',
    latitude: 39.3722,
    longitude: -104.8561,
    search_keywords: ['castle rock', 'castle rock co', 'the rock'],
    priority: 1,
  },
  {
    name: 'Aurora',
    state: 'CO',
    latitude: 39.7294,
    longitude: -104.8319,
    search_keywords: ['aurora', 'aurora co', 'aurora colorado'],
    priority: 1,
  },
  {
    name: 'Centennial',
    state: 'CO',
    latitude: 39.5791,
    longitude: -104.8769,
    search_keywords: ['centennial', 'centennial co'],
    priority: 2,
  },
  {
    name: 'Littleton',
    state: 'CO',
    latitude: 39.6133,
    longitude: -105.0166,
    search_keywords: ['littleton', 'littleton co'],
    priority: 2,
  },
  {
    name: 'Highlands Ranch',
    state: 'CO',
    latitude: 39.5419,
    longitude: -104.9708,
    search_keywords: ['highlands ranch', 'highlands ranch co', 'hr'],
    priority: 1,
  },
  {
    name: 'Lakewood',
    state: 'CO',
    latitude: 39.7047,
    longitude: -105.0814,
    search_keywords: ['lakewood', 'lakewood co'],
    priority: 2,
  },
  {
    name: 'Arvada',
    state: 'CO',
    latitude: 39.8028,
    longitude: -105.0875,
    search_keywords: ['arvada', 'arvada co', 'olde town arvada'],
    priority: 2,
  },
  {
    name: 'Thornton',
    state: 'CO',
    latitude: 39.8680,
    longitude: -104.9719,
    search_keywords: ['thornton', 'thornton co', 'north thornton'],
    priority: 1,
  },
  {
    name: 'Westminster',
    state: 'CO',
    latitude: 39.8367,
    longitude: -105.0372,
    search_keywords: ['westminster', 'westminster co'],
    priority: 2,
  },
  {
    name: 'Erie',
    state: 'CO',
    latitude: 40.0503,
    longitude: -105.0500,
    search_keywords: ['erie', 'erie co', 'erie colorado'],
    priority: 1,
  },
  {
    name: 'Lone Tree',
    state: 'CO',
    latitude: 39.5494,
    longitude: -104.8953,
    search_keywords: ['lone tree', 'lone tree co', 'ridgegate'],
    priority: 2,
  },
  {
    name: 'Broomfield',
    state: 'CO',
    latitude: 39.9205,
    longitude: -105.0867,
    search_keywords: ['broomfield', 'broomfield co'],
    priority: 2,
  },
  {
    name: 'Englewood',
    state: 'CO',
    latitude: 39.6480,
    longitude: -104.9878,
    search_keywords: ['englewood', 'englewood co'],
    priority: 3,
  },
  {
    name: 'Castle Pines',
    state: 'CO',
    latitude: 39.4622,
    longitude: -104.8953,
    search_keywords: ['castle pines', 'castle pines co', 'castle pines village'],
    priority: 2,
  },
  {
    name: 'Commerce City',
    state: 'CO',
    latitude: 39.8083,
    longitude: -104.9339,
    search_keywords: ['commerce city', 'commerce city co', 'reunion'],
    priority: 1,
  },
  {
    name: 'Brighton',
    state: 'CO',
    latitude: 39.9853,
    longitude: -104.8206,
    search_keywords: ['brighton', 'brighton co', 'brighton colorado'],
    priority: 1,
  },
  {
    name: 'Firestone',
    state: 'CO',
    latitude: 40.1125,
    longitude: -104.9367,
    search_keywords: ['firestone', 'firestone co'],
    priority: 2,
  },
  {
    name: 'Frederick',
    state: 'CO',
    latitude: 40.0992,
    longitude: -104.9372,
    search_keywords: ['frederick', 'frederick co', 'frederick colorado'],
    priority: 2,
  },
];
